services:
  - type: web
    name: assistente-alunos-1
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install -r requirements.txt && python generate_index.py
      mkdir -p static/css && echo "forçando inclusão de css" > static/css/.force
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        fromPrompt: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        fromPrompt: true
      - key: OPENAI_API_KEY
        fromPrompt: true
